name: Asset Uploader
on:
  push:
    paths:
      - "packages/asset-uploader/**/*"
      - ".github/workflows/asset-uploader.yml"
      - ".github/actions/publish-test/action.yaml"
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          workdir: ./packages/asset-uploader
          filter: "@webstudio-is/asset-uploader"
          token: ${{ secrets.NPM_TOKEN }}
