name: Cli tests

on:
  push:
    branches:
      - main
  pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: cli-${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  checks:
    timeout-minutes: 20

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      DATABASE_URL: postgres://
      AUTH_SECRET: test

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }} # HEAD commit instead of merge commit

      - uses: ./.github/actions/ci-setup

        # Testing fixtures for vercel template
      - name: Test cli --help flag
        working-directory: ./fixtures/webstudio-remix-vercel
        run: pnpm cli --help

      - name: Testing cli link command
        run: pnpm --filter='./fixtures/*' --sequential run fixtures:link

      - name: Testing cli sync command
        run: pnpm --filter='./fixtures/*' run --parallel fixtures:sync

      - name: Testing cli build command
        run: pnpm --filter='./fixtures/*' run --parallel fixtures:build

      - name: Test git diff
        # This command will fail if there are uncommitted changes, i.e something has broken
        run: git diff --name-only HEAD --exit-code

      - name: Show changed files
        if: ${{ failure() }}
        run: |
          echo "Changed files are:"
          git diff --name-only HEAD
