name: Design System
on:
  push:
    paths:
      - "packages/design-system/**/*"
      - ".github/workflows/design-system.yml"
      - ".github/actions/publish-test/action.yaml"
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          workdir: ./packages/design-system
          filter: "@webstudio-is/design-system"
          token: ${{ secrets.NPM_TOKEN }}
