name: Eslint Config
on:
  push:
    paths:
      - "packages/eslint-config-custom/**/*"
      - ".github/workflows/eslint-config-custom.yml"
      - ".github/actions/publish/action.yaml"
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          skip-build: true
          workdir: ./packages/eslint-config-custom
          filter: "@webstudio-is/eslint-config-custom"
          token: ${{ secrets.NPM_TOKEN }}
