name: Eslint Config Publish
on: 
 push:
   paths:
      - 'packages/eslint-config-custom/**/*'
      - '.github/workflows/eslint-config-custom-publish.yml'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: ./.github/actions/publish
       with:
        package: './packages/eslint-config-custom/package.json'
        token: ${{ secrets.NPM_TOKEN }}