name: Package tests (dry-run)
on:
  push:
    paths:
      - "packages/**/*"
      - ".github/workflows/package-tests.yml"
      - ".github/actions/publish-test/action.yaml"
jobs:
  publish-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish-test
        if: always()
        with:
          workdir: ./packages/asset-uploader
          filter: "@webstudio-is/asset-uploader"
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/publish-test
        if: always()
        with:
          workdir: ./packages/design-system
          filter: "@webstudio-is/design-system"
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/publish-test
        if: always()
        with:
          workdir: ./packages/eslint-config-custom
          filter: "@webstudio-is/eslint-config-custom"
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/publish-test
        if: always()
        with:
          workdir: ./packages/http-client
          filter: "@webstudio-is/http-client"
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/publish-test
        if: always()
        with:
          workdir: ./packages/icons
          filter: "@webstudio-is/icons"
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/publish-test
        if: always()
        with:
          workdir: ./packages/jest-config
          filter: "@webstudio-is/jest-config"
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/publish-test
        if: always()
        with:
          workdir: ./packages/react-sdk
          filter: "@webstudio-is/react-sdk"
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/publish-test
        if: always()
        with:
          workdir: ./packages/tsconfig
          filter: "@webstudio-is/tsconfig"
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/fonts
        if: always()
        with:
          workdir: ./packages/fonts
          filter: "@webstudio-is/fonts"
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/prisma-client
        if: always()
        with:
          workdir: ./packages/prisma-client
          filter: "@webstudio-is/prisma-client"
          token: ${{ secrets.NPM_TOKEN }}