name: Asset Uploader
on:
  push:
    paths:
      - "packages/**/*"
      - ".github/workflows/package-tests.yml"
      - ".github/actions/publish-test/action.yaml"
jobs:
  publish-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish-test
        with:
          workdir: ./packages/asset-uploader
          filter: "@webstudio-is/asset-uploader"
          token: ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/publish-test
        with:
          workdir: ./packages/design-system
          filter: "@webstudio-is/design-system"
          token: ${{ secrets.NPM_TOKEN }}
