name: Tsconfig
on:
  push:
    paths:
      - "packages/tsconfig/**/*"
      - ".github/workflows/tsconfig.yml"
      - ".github/actions/publish-test/action.yaml"
    branches:    
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish
        with:
          skip-build: true
          workdir: ./packages/tsconfig
          filter: "@webstudio-is/tsconfig"
          token: ${{ secrets.NPM_TOKEN }}
